### ISSUE TITLE
Change Crosswalk Version?

### ISSUE THREAD

**Issue by svox1** [MobileChromeApps/cordova-plugin-crosswalk-webview#23]
Hi,
thanks for this great plugin.

I use crosswalk for a while and test now your integration.
After playing around I ask me, how to change the Crosswalk version? I wanna use:
`12.41.296.9`
Is it possible to change this version for myself? 

Regards

**Comment by TanaseButcaru** [comment]
Changing ``11+`` with ``12+`` in this file ``libs/xwalk_core_library/xwalk.gradle`` should do the trick. (didn't tried it)
Also you can check the repo here https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/ ...from what I can see/understand from the repo & xwalk.gradle file, the cordova-plugin-crosswalk-webview installs a beta version of the library, why?

**Comment by svox1** [comment]
Thanks for the hint!

**Comment by agrieve** [comment]
FYI - just published a new version (v1.1.0) that sets the default version to crosswalk 13, and that makes the crosswalk version configurable via a `<preference>` (refer to README.md)

**Comment by Bnaya** [comment]
I've opened a feature request to crosswalk to made also canary version available
https://crosswalk-project.org/jira/browse/XWALK-3986
Vote it up please :)

**Comment by svox1** [comment]
@agrieve 
Thats great! Thx!

**Comment by Hirbod** [comment]
Seems like we had the same idea. See #24 and https://crosswalk-project.org/jira/browse/XWALK-3987

**Comment by TanaseButcaru** [comment]
My question about xwalk library version is still up!
To make it clear: the production ready version is the stable one that can be found <a href="https://crosswalk-project.org/documentation/downloads.html">here</a> (11.x), right?
So, if someone installs this plugin and immediately runs ``cordova build android``, then the app will use the latest beta version of the crosswalk webview (which is 13 in 1.1.0).

I think that the plugin releases should use only the latest stable version of crosswalk which is listed <a href="https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/">here</a>.

I think that this setup may confuse some users that doesn't pay attention to other details when they build their apps.

Instead of doing this:
```
<!-- These are all equivalent -->
<preference name="xwalkVersion" value="org.xwalk:xwalk_core_library_beta:13+" />
<preference name="xwalkVersion" value="xwalk_core_library_beta:13+" />
<preference name="xwalkVersion" value="13+" />
<preference name="xwalkVersion" value="13" />
```
... I propose something like this:
```
<preference name="xwalkChannel" value="CHANNEL" />
<preference name="xwalkVersion" value="VERSION" />
```
... where channel possible values are: stable, beta, canary and version - the version number.
Default values: channel - stable & version - latest stable version (11 for now).

**Comment by Hirbod** [comment]
@TanaseButcaru - best answer and best "way to go" :+1:

**Comment by TanaseButcaru** [comment]
Also, some little issues:
1. Right now when running ``cordova plugin add cordova-plugin-crosswalk-webview`` I get a "Not found" result.
2. If the project has more than one platform (ie: android & ios) the plugin is installed for all:
``
Uninstalling cordova-plugin-crosswalk-webview from android
Uninstalling cordova-plugin-crosswalk-webview from ios
``

**Comment by Hirbod** [comment]
@TanaseButcaru , this should be an own ticket, we should not mix up everything now

**Comment by TanaseButcaru** [comment]
@Hirbod you're right. I'll open another issue. :)
